language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t codekid20/docker-react -f Dockerfile.dev .

script:
  - docker run  -e CI=true codekid20/docker-react npm run test
